def problem_definition():
    return '''Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
    The first ten pentagonal numbers are:

                    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
    D = |Pk − Pj| is minimised; what is the value of D?'''


def pentagonal(n):
    return n * (3 * n - 1) // 2

pentagonals = set(pentagonal(n) for n in range(1, 10000))
for i in range(1, 10000):
    for j in range(i + 1, 10000):
        pi, pj = pentagonal(i), pentagonal(j)
        add = pi + pj
        sub = pj - pi  # reverse order so we get a positive number
        if (add in pentagonals and
            sub in pentagonals):
            print('We found {} and {} at {} and {}, difference is {}'.format(pi, pj, i, j, sub))
